apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: system
  labels:
    app.kubernetes.io/name: multinic-operator
spec:
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: multinic-operator
  ports:
  - name: http
    port: 18081
    targetPort: 18081
