apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
- inventory_service.yaml
images:
- name: controller
  newName: expert.harbor.bf.okestro.cloud/library/multinic-operator
  newTag: dev
