apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
- inventory_service.yaml
images:
- name: controller
  newName: nexus.okestro-k8s.com:50000/multinic-operator
  newTag: dev-20260111021627
