apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config
  namespace: system
data:
  CONTRABASS_ENDPOINT: ""
  CONTRABASS_TIMEOUT: "30s"
  CONTRABASS_INSECURE_TLS: "true"
  VIOLA_ENDPOINT: ""
  VIOLA_TIMEOUT: "30s"
  VIOLA_INSECURE_TLS: "false"
  OPENSTACK_TIMEOUT: "30s"
  OPENSTACK_INSECURE_TLS: "true"
  OPENSTACK_NEUTRON_ENDPOINT: ""
  OPENSTACK_NOVA_ENDPOINT: ""
  OPENSTACK_ENDPOINT_INTERFACE: "public"
  OPENSTACK_ENDPOINT_REGION: ""
  OPENSTACK_NODE_NAME_METADATA_KEY: ""
  OPENSTACK_PORT_ALLOWED_STATUSES: "ACTIVE,DOWN"
  DOWN_PORT_FAST_RETRY_MAX: "5"
  POLL_FAST_INTERVAL: "20s"
  POLL_SLOW_INTERVAL: "2m"
  POLL_ERROR_INTERVAL: "30s"
  POLL_FAST_WINDOW: "3m"
