apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config
  namespace: system
data:
  CONTRABASS_ENDPOINT: ""
  CONTRABASS_TIMEOUT: "30s"
  CONTRABASS_INSECURE_TLS: "true"
  VIOLA_ENDPOINT: ""
  VIOLA_TIMEOUT: "30s"
  VIOLA_INSECURE_TLS: "false"
  OPENSTACK_TIMEOUT: "30s"
  OPENSTACK_INSECURE_TLS: "true"
  OPENSTACK_NEUTRON_ENDPOINT: ""
  OPENSTACK_ENDPOINT_INTERFACE: "public"
  OPENSTACK_ENDPOINT_REGION: ""
