apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "multinic-operator.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multinic-operator.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.operatorConfig }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
