apiVersion: v1
kind: Secret
metadata:
  name: {{ include "multinic-operator.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multinic-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.operatorSecret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
